apiVersion: v1
entries:
  loyalty-level:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.788541+02:00
    description: A Helm chart for the loyalty level microservice of the StockTrader
      application.
    digest: 47c0a3705751331d3ac4a1bbcbe1cb4ba974f9c86e7a1b6b4dfe5357766bea64
    name: loyalty-level
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/loyalty-level-1.0.0.tgz
    version: 1.0.0
  messaging:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.789241+02:00
    description: A Helm chart for the messaging microservice of the StockTrader application.
    digest: a07ef51fa39889b1df94daa494d2d0200473b6eaba0ba8b3f5e3851886c7424d
    name: messaging
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/messaging-1.0.0.tgz
    version: 1.0.0
  notification-slack:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.790132+02:00
    description: A Helm chart for the slack notification microservice of the StockTrader
      application.
    digest: 1bababe60723edbf48330883f83dbb35348ae13339259546df248021a9e5812a
    name: notification-slack
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-slack-1.0.0.tgz
    version: 1.0.0
  notification-twitter:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.791033+02:00
    description: A Helm chart for the Twitter notification microservice of the StockTrader
      application.
    digest: ec17ba38e4c17cd08a60ceab41b103bb1f6d43d6265cff5b536832066f3b68c2
    name: notification-twitter
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-twitter-1.0.0.tgz
    version: 1.0.0
  portfolio:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.791962+02:00
    description: A Helm chart for the portfolio microservice of the StockTrader application.
    digest: f8184acd8b69e037e6b63a09c2b76e8093e9ef428a2b924d91a1ad876724048c
    name: portfolio
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/portfolio-1.0.0.tgz
    version: 1.0.0
  stock-quote:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.792809+02:00
    description: A Helm chart for the stock quote microservice of the StockTrader
      application.
    digest: df220d623b2ae4c1f93bd8d159e0262f03b68c5bfcd5b12d714ad0979cf523ad
    name: stock-quote
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stock-quote-1.0.0.tgz
    version: 1.0.0
  stocktrader-app:
  - apiVersion: v1
    created: 2018-05-08T16:53:40.794089+02:00
    description: IBM StockTrader application
    digest: 218d6dec3e0930040402198acfeade84fcabfa77a21f9ae7c00b9fc1808fe1aa
    name: stocktrader-app
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stocktrader-app-0.1.0.tgz
    version: 0.1.0
  trader:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-08T16:53:40.794792+02:00
    description: A Helm chart for the trader microservice of the StockTrader application.
    digest: c22e9aeeb812766143bd3069abdf29c7ec9121f8ec909bd76b5e2be66287c536
    name: trader
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/trader-1.0.0.tgz
    version: 1.0.0
generated: 2018-05-08T16:53:40.787383+02:00
