apiVersion: v1
entries:
  loyalty-level:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.928868+02:00
    description: A Helm chart for the loyalty level microservice of the StockTrader
      application.
    digest: 47c0a3705751331d3ac4a1bbcbe1cb4ba974f9c86e7a1b6b4dfe5357766bea64
    name: loyalty-level
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/loyalty-level-1.0.0.tgz
    version: 1.0.0
  messaging:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.92977+02:00
    description: A Helm chart for the messaging microservice of the StockTrader application.
    digest: a07ef51fa39889b1df94daa494d2d0200473b6eaba0ba8b3f5e3851886c7424d
    name: messaging
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/messaging-1.0.0.tgz
    version: 1.0.0
  notification-slack:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.930505+02:00
    description: A Helm chart for the slack notification microservice of the StockTrader
      application.
    digest: 1bababe60723edbf48330883f83dbb35348ae13339259546df248021a9e5812a
    name: notification-slack
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-slack-1.0.0.tgz
    version: 1.0.0
  notification-twitter:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.931369+02:00
    description: A Helm chart for the Twitter notification microservice of the StockTrader
      application.
    digest: 61d49676d3ce5ed9319575948e23f1a46cb972aa328d55ef6d4ce2d55f96106b
    name: notification-twitter
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-twitter-1.0.0.tgz
    version: 1.0.0
  portfolio:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.932148+02:00
    description: A Helm chart for the portfolio microservice of the StockTrader application.
    digest: f8184acd8b69e037e6b63a09c2b76e8093e9ef428a2b924d91a1ad876724048c
    name: portfolio
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/portfolio-1.0.0.tgz
    version: 1.0.0
  stock-quote:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.932896+02:00
    description: A Helm chart for the stock quote microservice of the StockTrader
      application.
    digest: df220d623b2ae4c1f93bd8d159e0262f03b68c5bfcd5b12d714ad0979cf523ad
    name: stock-quote
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stock-quote-1.0.0.tgz
    version: 1.0.0
  stocktrader-app:
  - apiVersion: v1
    created: 2018-05-22T13:04:22.935244+02:00
    description: IBM StockTrader application
    digest: 3913fb39ab2a27957f3d7361a85ad81f79a4ef640e71572970b5192e17d1a10f
    name: stocktrader-app
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stocktrader-app-0.1.0.tgz
    version: 0.1.0
  trader:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T13:04:22.935608+02:00
    description: A Helm chart for the trader microservice of the StockTrader application.
    digest: 436bf4a17a7fe7f71c99fe428ab778ac54711483d0a5cc09ecfa9c6394f706b9
    name: trader
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/trader-1.0.0.tgz
    version: 1.0.0
generated: 2018-05-22T13:04:22.927655+02:00
