apiVersion: v1
entries:
  loyalty-level:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.109053+02:00
    description: A Helm chart for the loyalty level microservice of the StockTrader
      application.
    digest: 47c0a3705751331d3ac4a1bbcbe1cb4ba974f9c86e7a1b6b4dfe5357766bea64
    name: loyalty-level
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/loyalty-level-1.0.0.tgz
    version: 1.0.0
  messaging:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.109752+02:00
    description: A Helm chart for the messaging microservice of the StockTrader application.
    digest: a07ef51fa39889b1df94daa494d2d0200473b6eaba0ba8b3f5e3851886c7424d
    name: messaging
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/messaging-1.0.0.tgz
    version: 1.0.0
  notification-slack:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.110448+02:00
    description: A Helm chart for the slack notification microservice of the StockTrader
      application.
    digest: 1bababe60723edbf48330883f83dbb35348ae13339259546df248021a9e5812a
    name: notification-slack
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-slack-1.0.0.tgz
    version: 1.0.0
  notification-twitter:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.111186+02:00
    description: A Helm chart for the Twitter notification microservice of the StockTrader
      application.
    digest: 61d49676d3ce5ed9319575948e23f1a46cb972aa328d55ef6d4ce2d55f96106b
    name: notification-twitter
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/notification-twitter-1.0.0.tgz
    version: 1.0.0
  portfolio:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.112584+02:00
    description: A Helm chart for the portfolio microservice of the StockTrader application.
    digest: 786ce30bf2e8104168c2e768a948524ec909947443f4f336fa6ce0cacbc63d0c
    name: portfolio
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/portfolio-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.111837+02:00
    description: A Helm chart for the portfolio microservice of the StockTrader application.
    digest: 2fd3c62aeb0384c24ead89c158fe55098734a8f0a09f1772eb24855fcae165a5
    name: portfolio
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/portfolio-1.0.0.tgz
    version: 1.0.0
  stock-quote:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.113179+02:00
    description: A Helm chart for the stock quote microservice of the StockTrader
      application.
    digest: df220d623b2ae4c1f93bd8d159e0262f03b68c5bfcd5b12d714ad0979cf523ad
    name: stock-quote
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stock-quote-1.0.0.tgz
    version: 1.0.0
  stocktrader-app:
  - apiVersion: v1
    created: 2018-05-22T16:21:49.117145+02:00
    description: IBM StockTrader application
    digest: 0745506b354436fcc7462de54e478fdd99616097f7ff432bb6b2d92f71101c50
    name: stocktrader-app
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stocktrader-app-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2018-05-22T16:21:49.115139+02:00
    description: IBM StockTrader application
    digest: d18907294b47585bc15746d331de3cb1f5a9f608ec5a50ab696e570063408706
    name: stocktrader-app
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/stocktrader-app-0.1.0.tgz
    version: 0.1.0
  trader:
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.118187+02:00
    description: A Helm chart for the trader microservice of the StockTrader application.
    digest: 9b59e0a13293005ab8a82ffd49efff7babcae9add0ea0ba4e4ec7b58098f6dd5
    name: trader
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/trader-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: icp-v1.0
    created: 2018-05-22T16:21:49.117457+02:00
    description: A Helm chart for the trader microservice of the StockTrader application.
    digest: 7c65300acb57b0adafd76e08c07aa44e24e4c0407441c5075adfb6c6de36c061
    name: trader
    urls:
    - https://raw.githubusercontent.com/jesusmah/stocktrader-helm-repo/master/docs/charts/trader-1.0.0.tgz
    version: 1.0.0
generated: 2018-05-22T16:21:49.108078+02:00
